name: API Tests with Newman
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman-Reporter-HTML-Extra
        run: npm install -g newman-reporter-htmlextra

      - name: Crear Carpeta Reportes
        run: mkdir -p reports
        
      - name: Run API tests
        run: newman run tests/Collection.json -e tests/Enviroments.json -r htmlextra --reporter-htmlextra-export reports/report_html-apis-githubactions.html

      - name: Reporte HTML
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report_html-apis-githubactions.html 
